version: '3.9'

services:
  arxivchat:
    image: ghcr.io/forward-operators/arxivchat:latest
    # build: .
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
     - ./app:/app
     - ./your_arxiv_data:/arxiv_data