version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - chroma
  chroma:
    image: ghcr.io/chroma-core/chroma:0.3.21
    ports:
      - "8000:8000"

volumes:
  chroma: